all:
	@more Makefile

install:
	npm install

build:
	npm run build

build-dev:
	npm run build:dev

lint:
	npm run lint

fmt:
	npm run fmt

test:
	npm run tsc
	npm run test

start:
	npm run start

clean:
	npm run clean
