version: "3.9"
services:
  web:
    container_name: web.local
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./docker/nginx/tls:/etc/nginx/tls:cached
      - ./public:/home/php_slim/public:cached
    logging:
      driver: "local"
      options:
        max-size: "10m"
  app:
    container_name: app.local
    build: .
    volumes:
      - ./docker/php/php8.ini-development:/usr/local/etc/php/php.ini:cached
      - ./docker/mysql/conf/my.client.cnf:/etc/mysql/my.cnf:cached
      - .:/home/php_slim:cached
    depends_on:
      - web
      - mysql
      - redis
    logging:
      driver: "local"
      options:
        max-size: "10m"
  redis:
    container_name: redis.local
    image: redis:6-alpine
    logging:
      driver: "local"
      options:
        max-size: "10m"
  mysql:
    container_name: mysql.local
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql:delegated
      - ./docker/mysql/conf/my80.cnf:/etc/mysql/my.cnf:cached
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:cached
    logging:
      driver: "local"
      options:
        max-size: "10m"
  mail:
    container_name: mail.local
    image: kanemu/maildev-with-iconv
    ports:
      - 8081:80
    logging:
      driver: "local"
      options:
        max-size: "10m"
  swagger:
    container_name: swagger.local
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./data/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      API_URL: openapi.yaml
    logging:
      driver: "local"
      options:
        max-size: "10m"

volumes:
  db-data: {}
