version: "3.3"
services:
  web:
    container_name: web.local
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./docker/nginx/tls:/etc/nginx/tls:cached
      - ./public:/home/php_slim/public:cached
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      webnet:
        ipv4_address: 192.168.1.30
  app:
    container_name: app.local
    build: .
    volumes:
      - ./docker/php/php7.ini:/usr/local/etc/php/php.ini:cached
      - ./docker/mysql/conf/my.client.cnf:/etc/mysql/my.cnf:cached
      - .:/home/php_slim:cached
    depends_on:
      - web
      - db
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      webnet:
        ipv4_address: 192.168.1.40
  cache:
    container_name: cache.local
    image: memcached:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      webnet:
        ipv4_address: 192.168.1.50
  db:
    container_name: db.local
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    volumes:
      - ./docker/mysql/conf/my55.cnf:/etc/mysql/my.cnf:cached
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:cached
      - db-data:/var/lib/mysql/data:delegated
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      webnet:
        ipv4_address: 192.168.1.60
  swagger:
    container_name: swagger.local
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./data/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      API_URL: openapi.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      webnet:
        ipv4_address: 192.168.1.70

networks:
  webnet:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 192.168.1.0/24

volumes:
  db-data:
