version: "3"
services:
  web:
    container_name: web.local
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./docker/data:/data
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/tls:/etc/nginx/tls:ro
      - ./public:/home/php_slim/public
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - webnet
  app:
    container_name: app.local
    build: .
    volumes:
      - ./docker/data:/data
      - ./docker/php/php7.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/mysql/conf/my.client.cnf:/etc/mysql/my.cnf:ro
      - .:/home/php_slim
    depends_on:
      - web
      - db
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - webnet
  cache:
    container_name: cache.local
    image: memcached:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - webnet
  db:
    container_name: db.local
    image: mysql:5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    volumes:
      - ./docker/data:/data
      - ./docker/mysql/conf/my55.cnf:/etc/mysql/my.cnf:ro
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - webnet

networks:
  webnet:

volumes:
  db-data:
