# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers
        environment:
          APP_ENV: dev
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: sample_slim_test
          MYSQL_USER: slim_user
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        command: [--character-set-server=utf8, --collation-server=utf8_general_ci, --default-storage-engine=innodb]      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/php_slim

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: docker run make composer/install
#      - run: make composer/install
#      - run: make db/test/migrate

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
      - run: make test
