# PHP CircleCI 2.1 configuration file
version: 2.1

executors:
  backbone-executor:
    machine:
      docker_layer_caching: false
    working_directory: ~/php_slim
jobs:
  lint_test_for_server:
    executor: backbone-executor
    steps:
      - checkout
      - run:
          command: |
            set -x
            docker network prune -f
            make docker/build
            make docker/up
            docker-compose logs
            docker ps
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-vendor-{{ checksum "composer.json" }}

      - run: make docker/composer/install ENV=dev

      - save_cache:
          paths:
            - ./vendor
          key: v1-vendor-{{ checksum "composer.json" }}
        
      # run tests!
      - run: make docker/lint
      - run: sudo apt-get update && sudo apt-get install -y mysql-client
      - run: mysql -h 127.0.0.1 -u root --password=mypass < ./docker/mysql/init/0_init.sql
      - run: make docker/db/test/migrate
      - run: make docker/test
  lint_test_for_client:
    executor: backbone-executor
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-client-package-{{ checksum "./client/package.json" }}
      - run: make docker/client/install
      - save_cache:
          paths:
            - ./client/node_modules
          key: v1-client-package-{{ checksum "./client/package.json" }}
      - run: make docker/client/lint
      - run: make docker/client/test
  echo:
    executor: backbone-executor
    steps:
      - run:
          command: |
            echo "TEST"
workflows:
  version: 2
  branch_test:
    jobs:
      - lint_test_for_server:
          filters:
            branches:
              ignore:
                - master
      - lint_test_for_client:
          filters:
            branches:
              ignore:
                - master
  deploy:
    jobs:
      - lint_test_for_server:
          filters:
            branches:
              only:
                - master
      - lint_test_for_client:
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - lint_test_for_server
            - lint_test_for_client
      - echo:
          requires:
            - hold

